version: '3.8'

services:
  furniture-ecommerce-fe:
    build: 
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: furniture-ecommerce-fe
    ports:
      - "3002:80"
    restart: always
