version: '3.8'

services:
  furniture-ecommerce-fe:
    build:
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: furniture-ecommerce-fe
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.furniture-ecommerce-fe.rule=Host(`furniture.daydevcore.com`)"
      - "traefik.http.routers.furniture-ecommerce-fe.entrypoints=websecure"
      - "traefik.http.routers.furniture-ecommerce-fe.tls.certresolver=myresolver" # <-- IMPORTANT: Change 'myresolver' to your Traefik cert resolver name (e.g., 'letsencrypt')
      - "traefik.http.services.furniture-ecommerce-fe.loadbalancer.server.port=80"
    networks:
      - proxy

networks:
  proxy:
    external: true
